// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFJBgnEPMGCKZ4OYf-9LVCuhVanKABvYk',
    appId: '1:1030674304120:web:58647f1fd1e113f1fe318d',
    messagingSenderId: '1030674304120',
    projectId: 'dbcocaroad',
    authDomain: 'dbcocaroad.firebaseapp.com',
    storageBucket: 'dbcocaroad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkOr9sVZbXDCjZUcjvS8P-qMcPPz4uLhs',
    appId: '1:1030674304120:android:4f8674b66a3c30e0fe318d',
    messagingSenderId: '1030674304120',
    projectId: 'dbcocaroad',
    storageBucket: 'dbcocaroad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXweQ6yOUXUjCuFpHCsKYXsYuxoezb7HI',
    appId: '1:1030674304120:ios:4161d7fe58c3904efe318d',
    messagingSenderId: '1030674304120',
    projectId: 'dbcocaroad',
    storageBucket: 'dbcocaroad.appspot.com',
    iosClientId: '1030674304120-ss211c4qbp6fsjqnatsn83csdb0bvj2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationCocaroad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXweQ6yOUXUjCuFpHCsKYXsYuxoezb7HI',
    appId: '1:1030674304120:ios:6fb17fb3615d25e1fe318d',
    messagingSenderId: '1030674304120',
    projectId: 'dbcocaroad',
    storageBucket: 'dbcocaroad.appspot.com',
    iosClientId: '1030674304120-i8fuli8knue8o0hmuval0bcslud3m19p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationCocaroad.RunnerTests',
  );
}
